name: flutter_beacon_plugin
description: A Flutter plugin allowing you to interact with beacons
version: 0.0.1
author: LinkDesk
homepage: https://linkdesk.com
repository: https://github.com/LinkDesk/flutter_beacon_plugin.git
issue_tracker: https://github.com/LinkDesk/flutter_beacon_plugin/issues
documentation: https://linkdesk.github.io/flutter_beacon_plugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1

dev_dependencies:
  pedantic: ^1.9.0
  json_serializable:  ^3.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.linkdesk.flutter_beacon_plugin
        pluginClass: FlutterBeaconPlugin
      ios:
        pluginClass: FlutterBeaconPlugin

